queue:
  connection:
    host: localhost

  exchange:
    name: beast
    durable: true
    autoDelete: false

instances:
  workers: 10
  engines: 3

log:
  console:
    level: silly
    colorize: true
    timestamp: 'MMMM Do YYYY, hh:mm:ss'
