queue:
  connection:
    host: localhost

  exchange:
    name: beast
    durable: true
    autoDelete: false

workers: 10

log:
  console:
    level: debug
    colorize: true
    timestamp: 'MMMM Do YYYY, hh:mm:ss'
